package org.Right.Api.Entity.Mapper;

import org.Right.Api.Entity.orgDepartment;
import org.Right.Api.Entity.orgDepartmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface orgDepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_department
     *
     * @mbggenerated
     */
    int countByExample(orgDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_department
     *
     * @mbggenerated
     */
    int deleteByExample(orgDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_department
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_department
     *
     * @mbggenerated
     */
    int insert(orgDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_department
     *
     * @mbggenerated
     */
    int insertSelective(orgDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_department
     *
     * @mbggenerated
     */
    List<orgDepartment> selectByExample(orgDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_department
     *
     * @mbggenerated
     */
    orgDepartment selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_department
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") orgDepartment record, @Param("example") orgDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_department
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") orgDepartment record, @Param("example") orgDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_department
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(orgDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_department
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(orgDepartment record);
}