package org.Right.Api.Entity.Mapper;

import org.Right.Api.Entity.RightUserAndMenu;
import org.Right.Api.Entity.RightUserAndMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RightUserAndMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_user_menu
     *
     * @mbggenerated
     */
    int countByExample(RightUserAndMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_user_menu
     *
     * @mbggenerated
     */
    int deleteByExample(RightUserAndMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_user_menu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_user_menu
     *
     * @mbggenerated
     */
    int insert(RightUserAndMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_user_menu
     *
     * @mbggenerated
     */
    int insertSelective(RightUserAndMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_user_menu
     *
     * @mbggenerated
     */
    List<RightUserAndMenu> selectByExample(RightUserAndMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_user_menu
     *
     * @mbggenerated
     */
    RightUserAndMenu selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_user_menu
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RightUserAndMenu record, @Param("example") RightUserAndMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_user_menu
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RightUserAndMenu record, @Param("example") RightUserAndMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_user_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RightUserAndMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_user_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RightUserAndMenu record);
}