package org.Right.Api.Entity.Mapper;

import org.Right.Api.Entity.RightMenuAndOrg;
import org.Right.Api.Entity.RightMenuAndOrgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RightMenuAndOrgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_menu_org
     *
     * @mbggenerated
     */
    int countByExample(RightMenuAndOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_menu_org
     *
     * @mbggenerated
     */
    int deleteByExample(RightMenuAndOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_menu_org
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_menu_org
     *
     * @mbggenerated
     */
    int insert(RightMenuAndOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_menu_org
     *
     * @mbggenerated
     */
    int insertSelective(RightMenuAndOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_menu_org
     *
     * @mbggenerated
     */
    List<RightMenuAndOrg> selectByExample(RightMenuAndOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_menu_org
     *
     * @mbggenerated
     */
    RightMenuAndOrg selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_menu_org
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RightMenuAndOrg record, @Param("example") RightMenuAndOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_menu_org
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RightMenuAndOrg record, @Param("example") RightMenuAndOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_menu_org
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RightMenuAndOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_menu_org
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RightMenuAndOrg record);
}