package org.Right.Api.Entity.Mapper;

import org.Right.Api.Entity.RightRoleAndUser;
import org.Right.Api.Entity.RightRoleAndUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RightRoleAndUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_role_user
     *
     * @mbggenerated
     */
    int countByExample(RightRoleAndUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_role_user
     *
     * @mbggenerated
     */
    int deleteByExample(RightRoleAndUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_role_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_role_user
     *
     * @mbggenerated
     */
    int insert(RightRoleAndUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_role_user
     *
     * @mbggenerated
     */
    int insertSelective(RightRoleAndUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_role_user
     *
     * @mbggenerated
     */
    List<RightRoleAndUser> selectByExample(RightRoleAndUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_role_user
     *
     * @mbggenerated
     */
    RightRoleAndUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_role_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RightRoleAndUser record, @Param("example") RightRoleAndUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_role_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RightRoleAndUser record, @Param("example") RightRoleAndUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_role_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RightRoleAndUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_role_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RightRoleAndUser record);
}