package org.Right.Api.Entity;

import java.io.Serializable;
import java.util.Date;

public class RightOrg implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right_org.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right_org.org_name
     *
     * @mbggenerated
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right_org.org_code
     *
     * @mbggenerated
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right_org.org_address
     *
     * @mbggenerated
     */
    private String orgAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right_org.org_tel
     *
     * @mbggenerated
     */
    private String orgTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right_org.org_parent_id
     *
     * @mbggenerated
     */
    private String orgParentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right_org.is_parent_org
     *
     * @mbggenerated
     */
    private Integer isParentOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right_org.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right_org.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right_org.create_org
     *
     * @mbggenerated
     */
    private String createOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right_org.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right_org.update_user
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right_org.update_org
     *
     * @mbggenerated
     */
    private String updateOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right_org.delete_time
     *
     * @mbggenerated
     */
    private Date deleteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right_org.delete_user
     *
     * @mbggenerated
     */
    private String deleteUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right_org.is_delete
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table right_org
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right_org.id
     *
     * @return the value of right_org.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right_org.id
     *
     * @param id the value for right_org.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right_org.org_name
     *
     * @return the value of right_org.org_name
     *
     * @mbggenerated
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right_org.org_name
     *
     * @param orgName the value for right_org.org_name
     *
     * @mbggenerated
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right_org.org_code
     *
     * @return the value of right_org.org_code
     *
     * @mbggenerated
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right_org.org_code
     *
     * @param orgCode the value for right_org.org_code
     *
     * @mbggenerated
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode == null ? null : orgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right_org.org_address
     *
     * @return the value of right_org.org_address
     *
     * @mbggenerated
     */
    public String getOrgAddress() {
        return orgAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right_org.org_address
     *
     * @param orgAddress the value for right_org.org_address
     *
     * @mbggenerated
     */
    public void setOrgAddress(String orgAddress) {
        this.orgAddress = orgAddress == null ? null : orgAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right_org.org_tel
     *
     * @return the value of right_org.org_tel
     *
     * @mbggenerated
     */
    public String getOrgTel() {
        return orgTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right_org.org_tel
     *
     * @param orgTel the value for right_org.org_tel
     *
     * @mbggenerated
     */
    public void setOrgTel(String orgTel) {
        this.orgTel = orgTel == null ? null : orgTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right_org.org_parent_id
     *
     * @return the value of right_org.org_parent_id
     *
     * @mbggenerated
     */
    public String getOrgParentId() {
        return orgParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right_org.org_parent_id
     *
     * @param orgParentId the value for right_org.org_parent_id
     *
     * @mbggenerated
     */
    public void setOrgParentId(String orgParentId) {
        this.orgParentId = orgParentId == null ? null : orgParentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right_org.is_parent_org
     *
     * @return the value of right_org.is_parent_org
     *
     * @mbggenerated
     */
    public Integer getIsParentOrg() {
        return isParentOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right_org.is_parent_org
     *
     * @param isParentOrg the value for right_org.is_parent_org
     *
     * @mbggenerated
     */
    public void setIsParentOrg(Integer isParentOrg) {
        this.isParentOrg = isParentOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right_org.create_time
     *
     * @return the value of right_org.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right_org.create_time
     *
     * @param createTime the value for right_org.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right_org.create_user
     *
     * @return the value of right_org.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right_org.create_user
     *
     * @param createUser the value for right_org.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right_org.create_org
     *
     * @return the value of right_org.create_org
     *
     * @mbggenerated
     */
    public String getCreateOrg() {
        return createOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right_org.create_org
     *
     * @param createOrg the value for right_org.create_org
     *
     * @mbggenerated
     */
    public void setCreateOrg(String createOrg) {
        this.createOrg = createOrg == null ? null : createOrg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right_org.update_time
     *
     * @return the value of right_org.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right_org.update_time
     *
     * @param updateTime the value for right_org.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right_org.update_user
     *
     * @return the value of right_org.update_user
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right_org.update_user
     *
     * @param updateUser the value for right_org.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right_org.update_org
     *
     * @return the value of right_org.update_org
     *
     * @mbggenerated
     */
    public String getUpdateOrg() {
        return updateOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right_org.update_org
     *
     * @param updateOrg the value for right_org.update_org
     *
     * @mbggenerated
     */
    public void setUpdateOrg(String updateOrg) {
        this.updateOrg = updateOrg == null ? null : updateOrg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right_org.delete_time
     *
     * @return the value of right_org.delete_time
     *
     * @mbggenerated
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right_org.delete_time
     *
     * @param deleteTime the value for right_org.delete_time
     *
     * @mbggenerated
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right_org.delete_user
     *
     * @return the value of right_org.delete_user
     *
     * @mbggenerated
     */
    public String getDeleteUser() {
        return deleteUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right_org.delete_user
     *
     * @param deleteUser the value for right_org.delete_user
     *
     * @mbggenerated
     */
    public void setDeleteUser(String deleteUser) {
        this.deleteUser = deleteUser == null ? null : deleteUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right_org.is_delete
     *
     * @return the value of right_org.is_delete
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right_org.is_delete
     *
     * @param isDelete the value for right_org.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_org
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RightOrg other = (RightOrg) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOrgName() == null ? other.getOrgName() == null : this.getOrgName().equals(other.getOrgName()))
            && (this.getOrgCode() == null ? other.getOrgCode() == null : this.getOrgCode().equals(other.getOrgCode()))
            && (this.getOrgAddress() == null ? other.getOrgAddress() == null : this.getOrgAddress().equals(other.getOrgAddress()))
            && (this.getOrgTel() == null ? other.getOrgTel() == null : this.getOrgTel().equals(other.getOrgTel()))
            && (this.getOrgParentId() == null ? other.getOrgParentId() == null : this.getOrgParentId().equals(other.getOrgParentId()))
            && (this.getIsParentOrg() == null ? other.getIsParentOrg() == null : this.getIsParentOrg().equals(other.getIsParentOrg()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getCreateOrg() == null ? other.getCreateOrg() == null : this.getCreateOrg().equals(other.getCreateOrg()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateUser() == null ? other.getUpdateUser() == null : this.getUpdateUser().equals(other.getUpdateUser()))
            && (this.getUpdateOrg() == null ? other.getUpdateOrg() == null : this.getUpdateOrg().equals(other.getUpdateOrg()))
            && (this.getDeleteTime() == null ? other.getDeleteTime() == null : this.getDeleteTime().equals(other.getDeleteTime()))
            && (this.getDeleteUser() == null ? other.getDeleteUser() == null : this.getDeleteUser().equals(other.getDeleteUser()))
            && (this.getIsDelete() == null ? other.getIsDelete() == null : this.getIsDelete().equals(other.getIsDelete()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_org
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOrgName() == null) ? 0 : getOrgName().hashCode());
        result = prime * result + ((getOrgCode() == null) ? 0 : getOrgCode().hashCode());
        result = prime * result + ((getOrgAddress() == null) ? 0 : getOrgAddress().hashCode());
        result = prime * result + ((getOrgTel() == null) ? 0 : getOrgTel().hashCode());
        result = prime * result + ((getOrgParentId() == null) ? 0 : getOrgParentId().hashCode());
        result = prime * result + ((getIsParentOrg() == null) ? 0 : getIsParentOrg().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getCreateOrg() == null) ? 0 : getCreateOrg().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateUser() == null) ? 0 : getUpdateUser().hashCode());
        result = prime * result + ((getUpdateOrg() == null) ? 0 : getUpdateOrg().hashCode());
        result = prime * result + ((getDeleteTime() == null) ? 0 : getDeleteTime().hashCode());
        result = prime * result + ((getDeleteUser() == null) ? 0 : getDeleteUser().hashCode());
        result = prime * result + ((getIsDelete() == null) ? 0 : getIsDelete().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_org
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orgName=").append(orgName);
        sb.append(", orgCode=").append(orgCode);
        sb.append(", orgAddress=").append(orgAddress);
        sb.append(", orgTel=").append(orgTel);
        sb.append(", orgParentId=").append(orgParentId);
        sb.append(", isParentOrg=").append(isParentOrg);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUser=").append(createUser);
        sb.append(", createOrg=").append(createOrg);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", updateOrg=").append(updateOrg);
        sb.append(", deleteTime=").append(deleteTime);
        sb.append(", deleteUser=").append(deleteUser);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}