package org.Right.Api.Entity.Mapper;

import org.Right.Api.Entity.departUser;
import org.Right.Api.Entity.departUserExample;
import java.util.List;

public interface departUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart_user
     *
     * @mbggenerated
     */
    int countByExample(departUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart_user
     *
     * @mbggenerated
     */
    int deleteByExample(departUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart_user
     *
     * @mbggenerated
     */
    int insert(departUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart_user
     *
     * @mbggenerated
     */
    int insertSelective(departUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart_user
     *
     * @mbggenerated
     */
    List<departUser> selectByExample(departUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart_user
     *
     * @mbggenerated
     */
    departUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") departUser record, @Param("example") departUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") departUser record, @Param("example") departUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(departUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(departUser record);
}