package org.Right.Api.Entity.Mapper;

import org.Right.Api.Entity.RightOrg;
import org.Right.Api.Entity.RightOrgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RightOrgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_org
     *
     * @mbggenerated
     */
    int countByExample(RightOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_org
     *
     * @mbggenerated
     */
    int deleteByExample(RightOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_org
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_org
     *
     * @mbggenerated
     */
    int insert(RightOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_org
     *
     * @mbggenerated
     */
    int insertSelective(RightOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_org
     *
     * @mbggenerated
     */
    List<RightOrg> selectByExample(RightOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_org
     *
     * @mbggenerated
     */
    RightOrg selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_org
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RightOrg record, @Param("example") RightOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_org
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RightOrg record, @Param("example") RightOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_org
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RightOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_org
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RightOrg record);
}