package org.Right.Api.Entity.Mapper;

import entity.RightRole;
import entity.RightRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RightRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_role
     *
     * @mbggenerated
     */
    int countByExample(RightRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_role
     *
     * @mbggenerated
     */
    int deleteByExample(RightRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_role
     *
     * @mbggenerated
     */
    int insert(RightRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_role
     *
     * @mbggenerated
     */
    int insertSelective(RightRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_role
     *
     * @mbggenerated
     */
    List<RightRole> selectByExample(RightRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_role
     *
     * @mbggenerated
     */
    RightRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_role
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RightRole record, @Param("example") RightRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_role
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RightRole record, @Param("example") RightRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RightRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RightRole record);
}