package org.Right.Api.Entity.Mapper;

import org.Right.Api.Entity.RightRoleAndMenu;
import org.Right.Api.Entity.RightRoleAndMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RightRoleAndMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_role_menu
     *
     * @mbggenerated
     */
    int countByExample(RightRoleAndMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_role_menu
     *
     * @mbggenerated
     */
    int deleteByExample(RightRoleAndMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_role_menu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_role_menu
     *
     * @mbggenerated
     */
    int insert(RightRoleAndMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_role_menu
     *
     * @mbggenerated
     */
    int insertSelective(RightRoleAndMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_role_menu
     *
     * @mbggenerated
     */
    List<RightRoleAndMenu> selectByExample(RightRoleAndMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_role_menu
     *
     * @mbggenerated
     */
    RightRoleAndMenu selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_role_menu
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RightRoleAndMenu record, @Param("example") RightRoleAndMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_role_menu
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RightRoleAndMenu record, @Param("example") RightRoleAndMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_role_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RightRoleAndMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_role_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RightRoleAndMenu record);
}