package org.Right.Api.Entity.Mapper;

import org.Right.Api.Entity.RightUser;
import org.Right.Api.Entity.RightUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RightUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_user
     *
     * @mbggenerated
     */
    int countByExample(RightUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_user
     *
     * @mbggenerated
     */
    int deleteByExample(RightUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_user
     *
     * @mbggenerated
     */
    int insert(RightUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_user
     *
     * @mbggenerated
     */
    int insertSelective(RightUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_user
     *
     * @mbggenerated
     */
    List<RightUser> selectByExample(RightUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_user
     *
     * @mbggenerated
     */
    RightUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RightUser record, @Param("example") RightUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RightUser record, @Param("example") RightUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RightUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RightUser record);
}